### ISSUE TITLE
Xamarin.Forms not show camera preview

### ISSUE THREAD

**Issue by gaf09** [Redth/ZXing.Net.Mobile#525]
Hi,

I use Xamarin.Forms > Android, the problem is given in some specific versions of Android ex: 5.1.1 .

When the scanner is opened (to read only QR), the camera is not previewed on the screen. The screen remains blank, the "Flash" button works. However, even without seeing the preview. The reader is working, because if the camera takes the QR code it reads it completely well anyway but without seeing it.
Currently only happens to me in Android API 22. What could it be ? 

My code:
```
var options = new ZXing.Mobile.MobileBarcodeScanningOptions();
options.PossibleFormats = new List<ZXing.BarcodeFormat>() {
	ZXing.BarcodeFormat.QR_CODE
};

scanPage = new ZXingScannerPage(options);
scanPage.OnScanResult += (result) =>
{
	scanPage.IsScanning = false;

	Device.BeginInvokeOnMainThread(() =>
	{
		var format = result?.BarcodeFormat.ToString() ?? string.Empty;
		var value = result?.Text ?? string.Empty;

		barCodeResultFormat = format;
		barCodeResultValue = value;

		// Show result
		Console.WriteLine(value);

		// Close screen
		page.Navigation.PopAsync();
	});
};

page.Navigation.PushAsync(scanPage);
```

Screenshot:
![screenshot_2017-04-11-13-21-17](https://cloud.githubusercontent.com/assets/1810534/24919458/23f86986-1eba-11e7-83f0-29b32e7640e7.png)

Thanks!

**Comment by axanth** [comment]
Facing the same issue!! please HELP

**Comment by A014304** [comment]
@axanth mine revived after several attempts, so wat i did was to re-install the package and update my xamarin.form to 3.0 and the rest of the Android.Support to 2.7. Miracle, it fixed by itself 👍 

Do give a try and let me know if tat works for you~~

**Comment by axanth** [comment]
Thank you vm man!! I will give it a try!

**Comment by axanth** [comment]
A014304 Android.Support what package exactly ? there are several and none has vesrion 2.7 exemple package is Xamarin.Android.Support.v4 and version is v25.4.0.2

**Comment by A014304** [comment]
@axanth **Android.Support 27.0.2**, which package, well i didn't really test which one i need, but they all come when u create xamarin project. I simply update Android.Support.v7.AppCompat, Android.Support.v7.CardView, Android.Support.v7.MediaRouter and Android.Support.v4 to v27.0.2. 
As well as Xamarin.Form to v3.0.0.482510. The latest Xamarin.Form v3.0.0.550146, i have not tested it yet. so maybe u wan to take note on tat.

**Comment by axanth** [comment]
Joe I tried with the version you mentioned but still the same!!! !@#!@ ... do you reference both ZXing.Net.Mobile and ZXing.Net.Mobile.Forms? If yes what version ? Do you have .Net Standard 2.0 as Shared library or PCL ?? Thanks in Advance

**Comment by axanth** [comment]
Joe I tried all that once more but nothing!! !#!@#!@$!@$. damn!!

**Comment by alexgg94** [comment]
Any update on this?

**Comment by axanth** [comment]
In my case it was something very simple but tricky to get imediatelly....I was using a theme that but background color in every window ...so the control works fine after I removed this on the theme xml it worked as a charm!!! I hope it helps someone else!

**Comment by alexgg94** [comment]
In my case, this behaviour only was happening the first time the application was running due to I was pushing the ZXingScannerPage before asking the user for the camera usage permissions. Once I start asking for permissions before pushing the ZXingScannerPage, all started to work as expected. 😊

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
