### ISSUE TITLE
Android crash after camera preview starts

### ISSUE THREAD

**Issue by xabre** [Redth/ZXing.Net.Mobile#932]
I have recently updated the library to the latest 3.0.0-beta5 version as I am migrating my app to AndroidX and API 29. 

Unfortunately I run into the following crash whenever the camera preview is turned on Android:

```
08-17 08:47:13.507 I/MonoDroid(11043): UNHANDLED EXCEPTION:
08-17 08:47:13.512 I/MonoDroid(11043): System.ArgumentNullException: Value cannot be null.
08-17 08:47:13.512 I/MonoDroid(11043): Parameter name: handle
08-17 08:47:13.513 I/MonoDroid(11043):   at ApxLabs.FastAndroidCamera.FastJavaByteArray..ctor (System.IntPtr handle, System.Boolean readOnly) [0x00016] in <9f646a7d069141bb922b3d2db31483e1>:0 
08-17 08:47:13.513 I/MonoDroid(11043):   at ZXing.Mobile.CameraAccess.CameraEventsListener.OnPreviewFrame (System.IntPtr data, Android.Hardware.Camera camera) [0x00000] in D:\a\ZXing.Net.Mobile\ZXing.Net.Mobile\ZXing.Net.Mobile\Android\CameraAccess\CameraEventsListener.android.cs:13 
08-17 08:47:13.513 I/MonoDroid(11043):   at ApxLabs.FastAndroidCamera.INonMarshalingPreviewCallbackInvoker.n_OnPreviewFrame_arrayBLandroid_hardware_Camera_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_data, System.IntPtr native_camera) [0x00010] in <9f646a7d069141bb922b3d2db31483e1>:0 
08-17 08:47:13.513 I/MonoDroid(11043):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.45(intptr,intptr,intptr,intptr)
```
Seems that a null IntPtr is passed to the FastJavaByteArray ctr in the OnPreviewFrame callback. Not sure why this is happening, camera permission is granted an the camera itself starts as I see a bit of the preview before the app crashes.

Any ideas, or possible workarounds?

Thanks

**Comment by lbulegato** [comment]
Same for me, did you find a fix ?
The problem came out because I am updating my project to AndroidX and API 29, and this is possible only using 3.0.0-beta5 version

**Comment by lbulegato** [comment]
The problem is in how you are using xamarin.essentials for permission.
I fixed in the following way:
add this call on the OnCreate 

```
protected override void OnCreate(Bundle savedInstanceState)
{
	base.OnCreate(savedInstanceState);
	**Xamarin.Essentials.Platform.Init(this, savedInstanceState);**

	...
}
```

and then when you are initialising the barcode check for the right permissions

  ```
var status = await Permissions.CheckStatusAsync<Permissions.Flashlight>();
            if (status != PermissionStatus.Granted)
                await Permissions.RequestAsync<Permissions.Flashlight>();
            else
            {
             //init your barcode
            }
```

**Comment by lbulegato** [comment]
Just another hint the crash is still here with the emulator, but it works with real devices.

**Comment by xabre** [comment]
Hmm... I am using `ZXing.Net.Mobile.Android.PermissionsHandler.RequestPermissionsAsync()` which internally checks both the camera and flashlight permission using Xamarin.Essentials.

Unfortunately still getting the same crash. Will try to explicitly request the permissions...

**Comment by xabre** [comment]
Seems that the exception was caused by a some sort of resolution miss-match.

I have commented out the `CameraResolutionSelector ` in `MobileBarcodeScanningOptions`. My implementation for CameraResolutionSelector was always returing the resolution with the greatest height...

`
 var options = new MobileBarcodeScanningOptions()
            {
                TryHarder = false,
                UseNativeScanning = true,
                PossibleFormats = new List<BarcodeFormat> { BarcodeFormat.QR_CODE },
                // CameraResolutionSelector = this.GetCameraResolution <--fixed it
            };
`

**Comment by lbulegato** [comment]
Did you manage to make it work with these changes?
From the latest tries, it works on google pixel devices but it crashes one plus smartphones.
I am going to try your suggestion.

**Comment by xabre** [comment]
Not setting the `CameraResolutionSelector` worked on OnePlus 7 too.

**Comment by lbulegato** [comment]
I can confirm that it works without using the CameraResolutionSelector, hope they will fix this bug

**Comment by knocte** [comment]
> I have recently updated the library to the latest 3.0.0-beta5 version

So can you confirm that this problem is a regression? I mean, you didn't have this problem with v2.4.1 right?

**Comment by lbulegato** [comment]
Yes correct it seems to be a regression, the last production version didn't have this issue.

**Comment by Dolphinsimon** [comment]
Not using the CameraResolutionSelector is not working for me. We do not set this parameter from start. We have to revert to version 2.4.1
